server.port: 8006
server.max-http-header-size: 50000

logging.file: logs/kb-service.log

spring.application.name: amcc-kb-service
spring.jackson.serialization.write_dates_as_timestamps: false

spring.cloud.stream.default-binder: cloud-kafka

spring.cloud.stream.bindings.kb.group: amcc.group.kb
spring.cloud.stream.bindings.kb.destination: amcc.topic.kb
spring.cloud.stream.bindings.kb.content-type: application/json
spring.cloud.stream.bindings.kb.binder: cloud-kafka

spring.cloud.stream.binders.cloud-kafka.type: kafka
spring.cloud.stream.binders.cloud-kafka.environment.spring.cloud.stream.kafka.binder.brokers: kafka.brokers.address
spring.cloud.stream.binders.cloud-kafka.environment.spring.cloud.stream.kafka.binder.zk-nodes: kafka.zk-nodes.address

spring.jpa.database: postgresql
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

spring.datasource.url: jdbc:postgresql://postgresql.address:5432/amcc-kb
spring.datasource.username: amcc
spring.datasource.password: s3cr3t.postgres.amcc
spring.datasource.tomcat.max-active: 5
spring.datasource.tomcat.max-wait: 10000
spring.datasource.tomcat.test-on-borrow: true
spring.datasource.tomcat.validation-query: SELECT 1
spring.datasource.tomcat.max-idle: 2
spring.datasource.tomcat.min-idle: 1
spring.datasource.tomcat.initial-size: 2

resource.id: oauth2/admin

# split with ','
public.resources: /resource/**,/**

service.source: amcc-kb

amcc.crm.service: http://192.168.8.144:8002
amcc.projection.service: http://192.168.8.144:8004
