server:
    port: 8084
    max-http-header-size: 50000


logging:
    file: logs/amcc-kb.log

spring:
    application:
        name: kb

    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:postgresql://192.168.8.39:5432/amcc-kb
        username: amcc
        password: s3cr3t.postgres.amcc
        tomcat:
            max-active: 5
            max-wait: 10000
            test-on-borrow: true
            validation-query: SELECT 1
            max-idle: 2
            min-idle: 1
            initial-size: 2